### ISSUE TITLE
`go install` support?

### ISSUE THREAD

**Issue by senpro-ingwersenk** [asticode/gotodo#10]
Hello!

I have a surprisingly bad habbit of leaving TODOs everywhere and not being really good at re-finding them so I wanted to use this tool to help me out :)
Unfortunately, it does not support `go install`; probably because the `*.go` files in the root are not `package main`.

Mind looking into this if you've got a minute?

Thanks and kind regards!

**Comment by asticode** [comment]
Which command are you using?

If I use `go install ./...`, it works properly 🤔

**Comment by senpro-ingwersenk** [comment]
I was using `go install github.com/asticode/go-astitodo@latest`

**Comment by asticode** [comment]
Does `go install github.com/asticode/go-astitodo/...@latest` work?

**Comment by senpro-ingwersenk** [comment]
Huh, that _did_ work. o.o Didn't even think of using `...` - not exactly common for `go install`. But hey, it's installed! Thanks =)
